export default function Head() {
  return (
    <>
      <title>kylerummens.com</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" type="image/x-icon" href="/favicons/favicon.ico"></link>
    </>
  )
}
